name: upload artifacts

on: push

env:
  FILE_NAME: "README.md"

jobs:
  Upload-artifact:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}
